[package]
name = "gitignoregen"
version = "0.1.0"
authors = ["Patrik Laurell <patrik.laurell@gmail.com>"]
edition = "2021"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
reqwest = "0.12.7"
tokio = { version = "1", features = ["full"] }

